from dotenv import load_dotenv
load_dotenv()

from typing import List
from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langchain_tavily import TavilySearch
from pydantic import BaseModel, Field


class Source(BaseModel):
    """Schema of source used by the agent."""

    url: str = Field(description="The URL of the source.")

class Answer(BaseModel):
    """Schema of each answer generated by the agent."""

    job_title: str = Field(description="The title of the job posting.")
    company_name: str = Field(description="The name of the company offering the job.")
    location: str = Field(description="The location of the job posting.")
    job_description: str = Field(description="The description of the job posting.")

class AgentResponse(BaseModel):
    """Schema of the agent's response."""

    answer: List[Answer] = Field(default_factory=list, description="The answers generated by the agent.")
    sources: List[Source] = Field(default_factory=list, description="List of sources used by the agent to generate the answer.")

llm = ChatOpenAI(model="gpt-5")
tools = [TavilySearch()]
agent = create_agent(model=llm, tools=tools, response_format=AgentResponse)


def main() -> None:
    print("Hello from langchain-course!")
    result = agent.invoke(
        {
            "messages": HumanMessage(
                content="Search for 10 job postings for an AI Engineer using LangChain in Hyderabad, India and list their details in a table format with the following columns: Job Title, Company Name, Location, and Job Description."
            )
        }
    )
    print(result)


if __name__ == "__main__":
    main()
